package com.foundyourdog.app.model;

import java.sql.Timestamp;

import com.foundyourdog.app.Validatable;

import lombok.Data;
import spark.Request;

@Data
public class ImageDetailResponse {
	// these overlap strongly with the DB record
	private String uuid;
	private String user_id;
	private Timestamp upload_date;
	private String tags;
	private String dog_id;
	private String status;
	// these are either transient or derived values
	private String uploadSignature;
	private String uploadUrl;
	private String apiKey;
	private String imageLocation;	// this is the exact response from the uploader
	private String imageUrl;		// this is generated by...us for now
	
	public ImageDetailResponse() {
		
	}
	
	public ImageDetailResponse(Image image) {
		// copy relevant bits
		this.uuid = image.getUuid();
		this.user_id = image.getUser_id();
		this.upload_date = image.getUpload_date();
		this.tags = image.getTags();
		this.dog_id = image.getDog_id();
		this.status = image.getStatus();
		this.setImageUrl(image.getImage_location());
	}

	public void setImageUrl(Request request, String imageLocation) {
		if (imageLocation.startsWith("/"))
			this.imageUrl = request.scheme() + "//" + request.host() + "/api/image" + imageLocation;
		else
			this.imageUrl = imageLocation;	// assume this got validated elsewhere
	}
}
