CREATE USER admin WITH PASSWORD '$PASSWD$';
CREATE DATABASE foundyourdog_$ENV$;
\connect foundyourdog_$ENV$

GRANT ALL PRIVILEGES ON DATABASE foundyourdog_$ENV$ TO admin;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO admin;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public to admin;